### ISSUE TITLE
404 on .netlify/identity/settings shortly after provisioning identity

### ISSUE THREAD

**Issue by kosirm** [netlify/netlify-identity-widget#102]
Hi, that widget is really great thing, works perfectly on netlify site, but when I develop locally (on cloud 9) I don't know how to set it up. I have a jekyll site and if I try to open identity widget I get 404 error:
`GET https://jekyll-infocube.c9users.io/.netlify/identity/settings 404 (Not Found)`
I actually don't know how can I add settings (netlify identity API endpoint) to widget. Thanks in advance for any advice. Sorry for using issues for help.

**Comment by ilyabo** [comment]
I experience the same error. This is due to CORS. Firefox has a more detailed error message than Chrome:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://mywebsite.ch/.netlify/identity/settings. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

**Comment by kosirm** [comment]
In Firefox (4.0) I don't get nothing, no error... just empty overlay like in chrome.

**Comment by bcomnes** [comment]
There are a few sharp edges around local development, as a consequence of our aim at zero configuration for the widget endpoint (e.g. it defaults to using the domain name of whatever its served from). 

We are planning on releasing better redirect support soon which should improve the local development flow soon™️.

**Comment by kosirm** [comment]
Thanks! That would be awesome !

**Comment by bcomnes** [comment]
Closing in favor of https://github.com/netlify/netlify-identity-widget/issues/40 but rest assured this is still on the roadmap.

**Comment by bcomnes** [comment]
Actually, going to repurpose this due to the recurring 404 problem.

**Comment by erquhart** [comment]
Will this also cover the CORS issue described here: https://github.com/netlify/netlify-cms/issues/1213#issuecomment-381202929

**Comment by bcomnes** [comment]
Wasn't aware of that issue.  I'll try to familiarize myself today.

**Comment by bcomnes** [comment]
OK, small followup:

> 404 on .netlify/identity/settings shortly after provisioning identity

If you run into this, trigger another deploy and the identity endpoint should be available after that.  Its a known issue we are aware of and are working on.

> CORS warning in local development

Local development should work fine, as the endpoint supports CORS.  It may be possible the CORS warning happens when the option call fails to the undeployed endpoint problem noted above.  There are some limitations during local development we will work on documenting and improving soon.

**Comment by calavera** [comment]
>  404 on .netlify/identity/settings shortly after provisioning identity

> If you run into this, trigger another deploy and the identity endpoint should be available after that. Its a known issue we are aware of and are working on.

Triggering a new deploy is no longer necessary.

**Comment by bcomnes** [comment]
Closing!

**Comment by audetcameron** [comment]
Hello. I wanted to share that in local netlify dev http://localhost:3000/login  and http://localhost:8888/login  I get the CORS issue while using fetch.  Is there a work around?  Using the react example.

**Comment by audetcameron** [comment]
> Hello. I wanted to share that in local netlify dev http://localhost:3000/login and http://localhost:8888/login I get the CORS issue while using fetch. Is there a work around? Using the react example.
_TL;DR_
Deploying anything makes the identity app works on localhost.

 **UPDATE**  My app was being built locally and not deployed. I was getting the issues/errors with identity.  However I pushed/deployed the unfinished app just to test if having a live deployment would help and it did.
