### ISSUE TITLE
Identity widget is requesting cms.bundle.js, causing net::ERR_ABORTED error

### ISSUE THREAD

**Issue by sw-yx** [netlify/netlify-identity-widget#107]
kind a disappointed that this is happening and i have no idea how to fix it... please help?

the site is at: <https://sw-yx.github.io/swyxblogtestbed/admin/>

and you can see the error here:

![image](https://user-images.githubusercontent.com/6764957/34239174-89898552-e640-11e7-88cc-eb263cab064b.png)

i have no idea what this cms.bundle.js is!

![image](https://user-images.githubusercontent.com/6764957/34239181-9643fd54-e640-11e7-9521-541bb4d1fd68.png)

**Comment by sw-yx** [comment]
never mind, it was because i was using a bad template `gatsby-starter-netlify-cms`

**Comment by Benaiah** [comment]
@sw-yx it looks like this is happening because the admin page is requesting the `cms.bundle.js` using a root-relative path (`/admin/cms.bundle.js`) which assumes you're running the CMS from `/admin/`. Since you're running it from `/swyxblogtestbed/admin/` instead, this isn't working correctly. I'll create a PR on `gatsby-starter-netlify-cms` to make that a relative path to fix the issue, but in the meantime you can edit the path in `static/admin/index.html` to the correct path to your `cms.bundle.js` (which should be `/swyxblogtestbed/admin/cms.bundle.js`) and rebuild the site.

**Comment by sw-yx** [comment]
nice detective work, thank you.

**Comment by sw-yx** [comment]
i think what i was confused by is where does `cms.bundle.js` come in. just appears out of nowhere and i was a little frustrated by this opaque magic. i guess I am used to being able to see everything when i work in gatsbyjs.
