### ISSUE TITLE
Display development URL, allow to be changed

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-identity-widget#148]
When developers work with multiple sites locally that all use Netlify Identity, a single URL often represents any of them at any time, e.g. `localhost:8000`. When in development mode, the Identity widget should display the current URL with a reset button for dumping the URL and providing the pop up to enter a new development URL.

Currently you have to 1. remember that this is happening when working across sites, and 2. manually delete site data to set a new URL each time the context changes.

**Comment by bcomnes** [comment]
We are working on a netlify dev proxy that should help solve this solution.  A possible solution is to implement a configuration api as well, so projects can specify endpoints.

**Comment by bcomnes** [comment]
Didn't mean to close, hit the wrong button.

**Comment by erquhart** [comment]
Thanks Bret. Fwiw, we could do this without a proxy or a config - just display the url being used and you can click to change. Should be a very small improvement, I'll try to find time for a PR soon.

**Comment by jlengstorf** [comment]
this has been implemented

**Comment by theredwillow** [comment]
@jlengstorf I'm still getting a static text at Identity > Services > Git Gateway. Am I missing something? I've renamed my repository and need to tell Netlify to go to that correct URL.

**Comment by jlengstorf** [comment]
@theredwillow this issue is tracking local development of Netlify Identity Widget — this repo doesn't have any control over the core Netlify Identity service

if you're trying to develop locally, the widget should ask for which site you want to use it with the first time you run the site locally, or give you the option to clear the localhost URL if you need to change it to use another site

if that's _not_ what you're hitting, please add a little more context and we can figure out where to look for answers

thanks!
