### ISSUE TITLE
Netlify Identity Widget appears broken on Netlify Dev

### ISSUE THREAD

**Issue by DavidChouinard** [netlify/netlify-identity-widget#185]
While using Netlify Dev (i.e. on a `....netlify.live` URL), the Netlify Identity Widget appears broken. Triggering `netlifyIdentity.open()` unhides a dark overlay over the entire content but doesn't open the model.

There are no Javascript errors in the console. Everything works fine when accessing `http://localhost:8000` directly. I've done `localStorage.removeItem('netlifySiteURL');` on both the netlify.live and localhost.

![brokenlogin](https://user-images.githubusercontent.com/388552/57333884-f78a7480-70d2-11e9-8577-656203cce2b8.gif)

**Comment by DavidChouinard** [comment]
Not sure if this is an issue with the identity widget or Netlify Dev @sw-yx

**Comment by sw-yx** [comment]
if it works without netlify dev and doesn’t work with netlify dev, its a netlify dev issue. better to file this at that repo. https://github.com/netlify/netlify-dev-plugin the —live feature is the newest one and needs a lot of work still.

**Comment by DavidChouinard** [comment]
Ok got it, will close here and open an issue on netlify-dev-plugin.

**Comment by kwak123** [comment]
Sorry to post in a zombie issue. Not totally related but this issue came up in my search for an answer. In case any one else comes across this, it appears that the widget won't open if you're not explicitly using `localhost` or `127.0.0.1`. Switching from an alias to `localhost` fixed it for me. Relevant line for why: https://github.com/netlify/netlify-identity-widget/blob/master/src/netlify-identity.js#L69

**Comment by ben519** [comment]
In my case, the widget wouldn't open until I forcibly ran `netlifyIdentity.open()` in the Console. After insert my siteURL into the widget, the widget opened on subsequent calls.
