### ISSUE TITLE
Add option to disable access_token check

### ISSUE THREAD

**Issue by BrandonNoad** [netlify/netlify-identity-widget#189]
In `netlify-identity-widget/src/netlify-identity.js`, there is a `runRoutes` function that checks if the url hash matches various tokens—`invite_token`, `confirmation_token`, etc.

One of the tokens it checks for is `access_token`, which I believe is needed when you are using an external OAuth provider.

I am using the Netlify Identity Widget for authentication, but I am also doing some OAuth2 stuff outside of Netlify Identity (for authorization), which conflicts with the `access_token` check and results in a `index.js:2177 Error: Gotrue-js: Failed to parse tokenResponse claims` error.

Is it possible to add an init option that we pass through to `runRoutes` that disables the `access_token` check? 

I can put up a PR if this is something you would like to add.

Thanks!

**Comment by sw-yx** [comment]
PR welcome.

**Comment by sw-yx** [comment]
im sorry i missed this for some reason i didnt get the notification the first time around. after reviewing this, i dont think its worth including, and suggest you either fork this package and own it, or use https://www.npmjs.com/package/patch-package to disable the check directly. im serious about it, its quite a good option!

thank you for the PR otherwise
