### ISSUE TITLE
Feature request: utilize refresh tokens

### ISSUE THREAD

**Issue by ricokahler** [netlify/netlify-identity-widget#233]
Sorry if this exists and I missed it, but I'd love if there was a way to refresh the tokens using the widget.

Could be something as simple as:

```js
netlifyIdentity.refresh(); // returns a promise
```

and

```js
netlifyIdentity.on('refresh', user => {/* ... */});
```

I'd be willing to spend some time one this if you're accepting.

**Comment by jlengstorf** [comment]
was in a conversation where this came up

this is important because without this support we are potentially returning an expired access token, and that's no fun for anyone. we don't show any way to do this and explicitly discourage going to the underlying `gotrue` instance, so right now it seems pretty challenging

this would need to include (I think) mobx updates to sync up the current user after a token refresh — I'm assuming it would look something like this: https://github.com/netlify/netlify-identity-widget/blob/05152b12587e5093940c004f647d59799daaa21f/src/netlify-identity.js#L138-L144

however, I don't know mobx, so I'm not exactly sure how all of that fits together at a quick glance

it seems like we'd need to call `gotrue.jwt()` under the hood, then update the current user in state with the updated access token

**Comment by ricokahler** [comment]
@jlengstorf I would assume that gotrue-js would have some sort of method for re-auth via refresh token built in but, IIRC, I don't remember seeing that in there.

Since this lib uses gotrue-js underneath, maybe we should start upstream?

**Comment by jlengstorf** [comment]
I heard from @futuregerald that this is possible now by accessing the underlying `gotrue` instance:

```js
netlifyIdentity.gotrue.currentUser().jwt(true).then((jwt)=>console.log(jwt))
```

this is how he's handling token refreshes in multiple production apps, so it's tested — the problem here seems to be missing documentation more than missing functionality

**Comment by minamme** [comment]
Even after refreshing token you need to reload the page. I don't know how to fix this :weary:
