### ISSUE TITLE
It looks like the development of this widget has stopped

### ISSUE THREAD

**Issue by guenam** [netlify/netlify-identity-widget#87]
After spending three days using the widget, it seems to me that some critical bugs have not been adressed in weeks. Has netlify abandonned / postponed this widget?

**Comment by biilmann** [comment]
Which issues are you referring to?

**Comment by guenam** [comment]
OK, I just realized I have been unfair here, thinking wrongly that an issue opened on Sept 25th was referring to the very recent issue #86. **My apology** for this unfounded statement.

That issue #86 is blocking though, at least for the author of #86 and me. 

The feeling I have that things have stopped on this widget: no roadmap (will Facebook / Twitter / Amazon be providers any time soon ?) ; no change in the code during the last month.
=> I'm sure you have plenty of more urgent tasks on your plate ; I just feel like I shouldn't use the widget in my code since its future is unclear.

I hope I'm not being unfair again! :-)

**Comment by biilmann** [comment]
No worries at all!

And good point on the localhost issue being a blocker in local dev. I think that final redirect depends on Gotrue rather than the widget itself, so in this case it would be good to open an issue on that over there. It makes sense to be able to specify localhost as the redirect target, but there's some security considerations there we need to consider.

We did just add support for Facebook in Gotrue and will soon be adding that as an option in the widget. For additional providers, we are considering whether to add them one by one to Gotrue, or do as suggested here https://github.com/netlify/gotrue/issues/122 and integrate with a wrapper.
