### ISSUE TITLE
Notification on availability

### ISSUE THREAD

**Issue by KrishnaPG** [netlify/netlify-identity-widget#96]
When loading the script asynchronously in browser from CDN
````
<script defer type="text/javascript" src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script>
````
is there anyway to detect when the `window.netlifyIdentity` object becomes available (after the script loads completing and initialize is done).

The reason being, the documentation asks to use below code 
````
// Bind to events
netlifyIdentity.on('init', user => console.log(user))
netlifyIdentity.on('login', user => console.log(user))
 ...
````
but without knowing when `netlifyIdentity` object would be available to use, we are running into the risk of using 'undefined' object.

![image](https://user-images.githubusercontent.com/4610831/32686744-2ee403fe-c6d1-11e7-8dab-bb607d019359.png)

Forcing synchronous load is possible, but would prefer to keep it async for better load performance.

**Comment by bcomnes** [comment]
Async script tag loading APIs are fairly though to get right. Any suggestions on how you would like to see this done?  

IIRC deferred scripts execute before the `DOMContentLoaded` event fires, and we assign to the window object synchronously https://github.com/netlify/netlify-identity-widget/blob/master/src/index.js#L7 so it should be safe to assume `window.netlifyIdentity` will be available at that point.

But we also fire the init method automatically on `DOMContentLoaded` https://github.com/netlify/netlify-identity-widget/blob/master/src/index.js#L11 so depending on the order you load things, you might miss the `init` event.  

If you need precise control over the initialization of the widget you are also free to use the module API which doesn't automatically call init.  It was assumed this API would be primarily consumed through browserify or webpack during the design of this module.  But since its packaged as a UMD, loading it in as as script tag should assign it to the window object as `netlifyIdentity` automatically.  Its available at:

```html
// Slightly different URL
<script defer type="text/javascript" src="https://identity.netlify.com/v1/netlify-identity.js"></script>
<script>
  document.addEventListener("DOMContentLoaded", () => {
    netlifyIdentity.init();
  });
</script>
```

**Comment by KrishnaPG** [comment]
Guess, you are right.

In the ReadMe documentation, the usage example used the `defer` option and I kind of liked it. But eventually it would create a chicken-and-egg problem. 

The usual synchronous script loading method (without defer) is working - I will use it. Thanks for your time and good work on sharing this library. It is useful.

**Comment by bcomnes** [comment]
Doh! You are right.  We should probably clarify that.

**Comment by KrishnaPG** [comment]
I am now trying this widget in a Vue.js application and have few questions, since I am loading these vue components dynamically.

- I am planning to call the `netlifyIdentity.init` on mount of the dynamic components. Now, the concern is: is it safe to call `netlifyIdentity.init()` multiple times (since there may be multiple dynamic components)
- What is the best way to identify if there is currently a logged-in user or not? Something like `netlifyIdentity.currentUser` ?? or do we have track the login/logout events and store the objects globally and refer to them? My only concern is if we miss these events (for whatever reason) then we loose important information.

**Comment by bcomnes** [comment]
If you are using the module, you should only call `.init` once.  Typically somewhere near the entry point of your app, you should import the module and call `.init` once.    

Throughout the app, you can import the identity module at the component level and interact with it, like call `.open` and `.close` and read state off of `.gotrue` which is a reference to the internally managed https://github.com/netlify/gotrue-js instance.  

Because the module essentially represents a globally shared object similar to a window object reference, you should subscribe to the events emitted by it early on in your app initialization process so that as different components interact with the widget, all parts of your app can know about it.  For example, having a single event listener that passes event data off to something like a redux store that keeps track of the identity state for your whole app is one way of managing this.

**Comment by bcomnes** [comment]
At some point we should probably guard for multiple init calls so it isn't an issue.

**Comment by KrishnaPG** [comment]
I think the problem is, right now the `init` method is doing both UI initialization (DOM manipulation for login/logout buttons), as well as the store initialization.

Because of this dual role it is become difficult to make the `init` call just once. For example, consider the below case:

- In the router (where no page is yet loaded, hence no DOM), I want to check if there is a current valid user (from local storage, perhaps from previous session, still hot and active). If so, redirect the route to direct dashboard (without hitting the login page). Else, redirect to login page

Now in this case, to get the current user (from local store), I need to call the `init` method. Without calling the `init` method, the `currentUser` method is returning null. So, the first `init` is happening in the router (even before any DOM is ready).

Then when the dashboard page or login page comesup, there is no way to just modify the DOM / buttons without having to call `init` again.

It would be great, if these two (DOM init and Store init) can be separated out.

**Comment by KrishnaPG** [comment]
Created separate issues for the `init` method refactor case: https://github.com/netlify/netlify-identity-widget/issues/111
